# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'locationFrame.ui'
#
# Created: Mon Jan  5 11:58:41 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LocationFrame(object):
    def setupUi(self, LocationFrame):
        LocationFrame.setObjectName("LocationFrame")
        LocationFrame.resize(434, 285)
        LocationFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        LocationFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout = QtGui.QVBoxLayout(LocationFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.locationLabel = QtGui.QLabel(LocationFrame)
        self.locationLabel.setOpenExternalLinks(True)
        self.locationLabel.setObjectName("locationLabel")
        self.verticalLayout.addWidget(self.locationLabel)
        self.lowerFrame = QtGui.QFrame(LocationFrame)
        self.lowerFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.lowerFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.lowerFrame.setObjectName("lowerFrame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.lowerFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.amFrame = QtGui.QFrame(self.lowerFrame)
        self.amFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.amFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.amFrame.setObjectName("amFrame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.amFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.amTop = QtGui.QLabel(self.amFrame)
        self.amTop.setObjectName("amTop")
        self.verticalLayout_4.addWidget(self.amTop)
        self.amLabel = QtGui.QLabel(self.amFrame)
        self.amLabel.setMaximumSize(QtCore.QSize(120, 120))
        self.amLabel.setText("")
        self.amLabel.setPixmap(QtGui.QPixmap("icons/am-clear.jpg"))
        self.amLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.amLabel.setObjectName("amLabel")
        self.verticalLayout_4.addWidget(self.amLabel)
        self.amDes = QtGui.QLabel(self.amFrame)
        self.amDes.setObjectName("amDes")
        self.verticalLayout_4.addWidget(self.amDes)
        self.amPercChance = QtGui.QLabel(self.amFrame)
        self.amPercChance.setObjectName("amPercChance")
        self.verticalLayout_4.addWidget(self.amPercChance)
        self.horizontalLayout_3.addWidget(self.amFrame)
        self.tempFrame = QtGui.QFrame(self.lowerFrame)
        self.tempFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tempFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.tempFrame.setObjectName("tempFrame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tempFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tempHigh = QtGui.QLabel(self.tempFrame)
        self.tempHigh.setObjectName("tempHigh")
        self.verticalLayout_5.addWidget(self.tempHigh)
        self.tempLow = QtGui.QLabel(self.tempFrame)
        self.tempLow.setObjectName("tempLow")
        self.verticalLayout_5.addWidget(self.tempLow)
        self.horizontalLayout_3.addWidget(self.tempFrame)
        self.pmFrame = QtGui.QFrame(self.lowerFrame)
        self.pmFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pmFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.pmFrame.setObjectName("pmFrame")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.pmFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pmTop = QtGui.QLabel(self.pmFrame)
        self.pmTop.setObjectName("pmTop")
        self.verticalLayout_6.addWidget(self.pmTop)
        self.pmLabel = QtGui.QLabel(self.pmFrame)
        self.pmLabel.setMaximumSize(QtCore.QSize(120, 120))
        self.pmLabel.setText("")
        self.pmLabel.setPixmap(QtGui.QPixmap("icons/pm-clear.jpg"))
        self.pmLabel.setObjectName("pmLabel")
        self.verticalLayout_6.addWidget(self.pmLabel)
        self.pmDes = QtGui.QLabel(self.pmFrame)
        self.pmDes.setObjectName("pmDes")
        self.verticalLayout_6.addWidget(self.pmDes)
        self.pmPercChance = QtGui.QLabel(self.pmFrame)
        self.pmPercChance.setObjectName("pmPercChance")
        self.verticalLayout_6.addWidget(self.pmPercChance)
        self.horizontalLayout_3.addWidget(self.pmFrame)
        self.verticalLayout.addWidget(self.lowerFrame)

        self.retranslateUi(LocationFrame)
        QtCore.QMetaObject.connectSlotsByName(LocationFrame)

    def retranslateUi(self, LocationFrame):
        LocationFrame.setWindowTitle(QtGui.QApplication.translate("LocationFrame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.locationLabel.setText(QtGui.QApplication.translate("LocationFrame", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Location</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.amTop.setText(QtGui.QApplication.translate("LocationFrame", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">AM</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.amDes.setText(QtGui.QApplication.translate("LocationFrame", "<html><head/><body><p align=\"center\">AM Description</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.amPercChance.setText(QtGui.QApplication.translate("LocationFrame", "AM Perc", None, QtGui.QApplication.UnicodeUTF8))
        self.tempHigh.setText(QtGui.QApplication.translate("LocationFrame", "<html><head/><body><p align=\"center\">Temp High</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tempLow.setText(QtGui.QApplication.translate("LocationFrame", "<html><head/><body><p align=\"center\">Temp Low</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pmTop.setText(QtGui.QApplication.translate("LocationFrame", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">PM</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pmDes.setText(QtGui.QApplication.translate("LocationFrame", "<html><head/><body><p align=\"center\">PM Description</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pmPercChance.setText(QtGui.QApplication.translate("LocationFrame", "PM Perc", None, QtGui.QApplication.UnicodeUTF8))

