# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weathertrek.ui'
#
# Created: Fri Jan  2 00:34:00 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 528)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startLabel = QtGui.QLabel(self.groupBox)
        self.startLabel.setObjectName("startLabel")
        self.horizontalLayout_2.addWidget(self.startLabel)
        self.startText = QtGui.QLineEdit(self.groupBox)
        self.startText.setObjectName("startText")
        self.horizontalLayout_2.addWidget(self.startText)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.endLabel = QtGui.QLabel(self.groupBox_2)
        self.endLabel.setObjectName("endLabel")
        self.horizontalLayout.addWidget(self.endLabel)
        self.endText = QtGui.QLineEdit(self.groupBox_2)
        self.endText.setObjectName("endText")
        self.horizontalLayout.addWidget(self.endText)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.reportTab = QtGui.QTabWidget(self.centralwidget)
        self.reportTab.setEnabled(False)
        self.reportTab.setObjectName("reportTab")
        self.todayTab = QtGui.QWidget()
        self.todayTab.setObjectName("todayTab")
        self.todayLayoutMain = QtGui.QVBoxLayout(self.todayTab)
        self.todayLayoutMain.setObjectName("todayLayoutMain")
        self.todayScroll = QtGui.QScrollArea(self.todayTab)
        self.todayScroll.setWidgetResizable(True)
        self.todayScroll.setObjectName("todayScroll")
        self.todayScrollArea = QtGui.QWidget()
        self.todayScrollArea.setGeometry(QtCore.QRect(0, 0, 558, 203))
        self.todayScrollArea.setObjectName("todayScrollArea")
        self.todayLayout = QtGui.QVBoxLayout(self.todayScrollArea)
        self.todayLayout.setObjectName("todayLayout")
        self.todayDate = QtGui.QLabel(self.todayScrollArea)
        self.todayDate.setObjectName("todayDate")
        self.todayLayout.addWidget(self.todayDate)
        self.todayScroll.setWidget(self.todayScrollArea)
        self.todayLayoutMain.addWidget(self.todayScroll)
        self.reportTab.addTab(self.todayTab, "")
        self.tomorrowTab = QtGui.QWidget()
        self.tomorrowTab.setObjectName("tomorrowTab")
        self.tomorrowLayoutMain = QtGui.QVBoxLayout(self.tomorrowTab)
        self.tomorrowLayoutMain.setObjectName("tomorrowLayoutMain")
        self.tomorrowScroll = QtGui.QScrollArea(self.tomorrowTab)
        self.tomorrowScroll.setWidgetResizable(True)
        self.tomorrowScroll.setObjectName("tomorrowScroll")
        self.tomorrowScrollArea = QtGui.QWidget()
        self.tomorrowScrollArea.setGeometry(QtCore.QRect(0, 0, 558, 203))
        self.tomorrowScrollArea.setObjectName("tomorrowScrollArea")
        self.tomorrowLayout = QtGui.QVBoxLayout(self.tomorrowScrollArea)
        self.tomorrowLayout.setObjectName("tomorrowLayout")
        self.tomorrowDate = QtGui.QLabel(self.tomorrowScrollArea)
        self.tomorrowDate.setObjectName("tomorrowDate")
        self.tomorrowLayout.addWidget(self.tomorrowDate)
        self.tomorrowScroll.setWidget(self.tomorrowScrollArea)
        self.tomorrowLayoutMain.addWidget(self.tomorrowScroll)
        self.reportTab.addTab(self.tomorrowTab, "")
        self.twoTab = QtGui.QWidget()
        self.twoTab.setObjectName("twoTab")
        self.twoLayoutMain = QtGui.QVBoxLayout(self.twoTab)
        self.twoLayoutMain.setObjectName("twoLayoutMain")
        self.twoScroll = QtGui.QScrollArea(self.twoTab)
        self.twoScroll.setWidgetResizable(True)
        self.twoScroll.setObjectName("twoScroll")
        self.twoScrollArea = QtGui.QWidget()
        self.twoScrollArea.setGeometry(QtCore.QRect(0, 0, 558, 203))
        self.twoScrollArea.setObjectName("twoScrollArea")
        self.twoLayout = QtGui.QVBoxLayout(self.twoScrollArea)
        self.twoLayout.setObjectName("twoLayout")
        self.twoDate = QtGui.QLabel(self.twoScrollArea)
        self.twoDate.setObjectName("twoDate")
        self.twoLayout.addWidget(self.twoDate)
        self.twoScroll.setWidget(self.twoScrollArea)
        self.twoLayoutMain.addWidget(self.twoScroll)
        self.reportTab.addTab(self.twoTab, "")
        self.threeTab = QtGui.QWidget()
        self.threeTab.setObjectName("threeTab")
        self.threeLayoutMain = QtGui.QVBoxLayout(self.threeTab)
        self.threeLayoutMain.setObjectName("threeLayoutMain")
        self.threeScroll = QtGui.QScrollArea(self.threeTab)
        self.threeScroll.setWidgetResizable(True)
        self.threeScroll.setObjectName("threeScroll")
        self.threeScrollArea = QtGui.QWidget()
        self.threeScrollArea.setGeometry(QtCore.QRect(0, 0, 558, 203))
        self.threeScrollArea.setObjectName("threeScrollArea")
        self.threeLayout = QtGui.QVBoxLayout(self.threeScrollArea)
        self.threeLayout.setObjectName("threeLayout")
        self.threeDate = QtGui.QLabel(self.threeScrollArea)
        self.threeDate.setObjectName("threeDate")
        self.threeLayout.addWidget(self.threeDate)
        self.threeScroll.setWidget(self.threeScrollArea)
        self.threeLayoutMain.addWidget(self.threeScroll)
        self.reportTab.addTab(self.threeTab, "")
        self.fourTab = QtGui.QWidget()
        self.fourTab.setObjectName("fourTab")
        self.fourLayoutMain = QtGui.QVBoxLayout(self.fourTab)
        self.fourLayoutMain.setObjectName("fourLayoutMain")
        self.fourScroll = QtGui.QScrollArea(self.fourTab)
        self.fourScroll.setWidgetResizable(True)
        self.fourScroll.setObjectName("fourScroll")
        self.fourScrollArea = QtGui.QWidget()
        self.fourScrollArea.setGeometry(QtCore.QRect(0, 0, 558, 203))
        self.fourScrollArea.setObjectName("fourScrollArea")
        self.fourLayout = QtGui.QVBoxLayout(self.fourScrollArea)
        self.fourLayout.setObjectName("fourLayout")
        self.fourDate = QtGui.QLabel(self.fourScrollArea)
        self.fourDate.setObjectName("fourDate")
        self.fourLayout.addWidget(self.fourDate)
        self.fourScroll.setWidget(self.fourScrollArea)
        self.fourLayoutMain.addWidget(self.fourScroll)
        self.reportTab.addTab(self.fourTab, "")
        self.verticalLayout_3.addWidget(self.reportTab)
        self.startButton = QtGui.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_3.addWidget(self.startButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.reportTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Weather Trek", None, QtGui.QApplication.UnicodeUTF8))
        self.startLabel.setText(QtGui.QApplication.translate("MainWindow", "Starting Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.endLabel.setText(QtGui.QApplication.translate("MainWindow", "Ending Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.todayDate.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Enter Data Above</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.reportTab.setTabText(self.reportTab.indexOf(self.todayTab), QtGui.QApplication.translate("MainWindow", "Today", None, QtGui.QApplication.UnicodeUTF8))
        self.tomorrowDate.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Date</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.reportTab.setTabText(self.reportTab.indexOf(self.tomorrowTab), QtGui.QApplication.translate("MainWindow", "Tomorrow", None, QtGui.QApplication.UnicodeUTF8))
        self.twoDate.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Date</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.reportTab.setTabText(self.reportTab.indexOf(self.twoTab), QtGui.QApplication.translate("MainWindow", "Two Days", None, QtGui.QApplication.UnicodeUTF8))
        self.threeDate.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Date</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.reportTab.setTabText(self.reportTab.indexOf(self.threeTab), QtGui.QApplication.translate("MainWindow", "Three Days", None, QtGui.QApplication.UnicodeUTF8))
        self.fourDate.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Date</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.reportTab.setTabText(self.reportTab.indexOf(self.fourTab), QtGui.QApplication.translate("MainWindow", "Four Days", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Get Weather", None, QtGui.QApplication.UnicodeUTF8))

